root_dir = '/home/junchen/git/pyirt/'
import sys
# import matplotlib.pyplot as plt
sys.path.insert(0,root_dir)
import random
import numpy as np
import utl

num_theta = 200
num_beta = 8
num_alpha = 4

# Total number of observation is 200*8*4

theta_vec = np.linspace(-2.0,4.0,num = num_theta)
beta_vec = np.linspace(-2.0, 2.0, num = num_beta)
alpha_vec = np.linspace(0.5, 2.0, num = num_alpha)

'''
create the matrix
'''

with open(root_dir + 'data/sim_data.txt','w') as f:
    for i in range(num_theta):
        for j in range(num_beta):
            for k in range(num_alpha):
                # compute eid
                eid = (j*num_alpha)+k

                theta = theta_vec[i]
                beta = beta_vec[j]
                alpha = alpha_vec[k]
                response_prob = utl.tools.irt_fnc(theta, beta, alpha=alpha)
                response = int(random.random() <= response_prob)
                f.write('{},{},{},{},{},{}\n'.format(response, i,eid, theta, beta, alpha))



'''
Simulate the dataset from Daniel and Joshua(2009)

user size: 500,1000,1500
item number: 40,80

+++++++ Unfinished! ++++++

alpha is generated by lognornmal with mean 0
beta is genreated by
'''
